### ISSUE TITLE
Delay in response of robot during Teleop

### ISSUE THREAD

**Issue by alifaraji03** [WCR-FRC-2016/2017rep#17]

**Comment by alifaraji03** [comment]
Might be associated with closing the NAVX chip when there is no NAVX chip.

**Comment by alifaraji03** [comment]
Possible reason: https://www.chiefdelphi.com/forums/showthread.php?t=136304

**Comment by haywoodsloan** [comment]
Most recent testing shows the issue to be in the closing of the NavX chip reference at the beginning of TeleOp. Made the NavX chip closing a parallel process to changing the motor control mode, appears to have solved the problem, but needs more testing on a fully functional robot.

**Comment by alifaraji03** [comment]
NavX seems to be the problem. New library fixes a lot of bugs. Closing because issue has not reappeared.
