### ISSUE TITLE
Decide drive train type

### ISSUE THREAD

**Issue by alifaraji03** [WCR-FRC-2016/2017rep#2]
We need to consider not only what the drive train is going to look like, but also how we want to control the drive train this year.

**Comment by haywoodsloan** [comment]
Hey guys we decided on a tank drive this year!

**Comment by haywoodsloan** [comment]
<<Test>>

**Comment by gregSchwartz18** [comment]
4-6 Sim base
2 may be mini-sims
Encoders for left and right sides of drive
side motors run in unison
may get encoders on each side
Assume Arcade
Autonomous: Drive forward, turn
May need to throttle turning relative to forward speed
2-3 motors per side

**Comment by alifaraji03** [comment]
Seems like we are leaning towards a 6 sim base. So we have gone ahead and created a six motor option in Teleop.vi that allows you to switch between 4 and 6 motors.
