### ISSUE TITLE
Setup Gear Motor

### ISSUE THREAD

**Issue by alifaraji03** [WCR-FRC-2016/2017rep#23]
Initial have it controlled with buttons that need to be hold to move the motor. Eventually, limit switches will control the gear mechanism.

**Comment by alifaraji03** [comment]
The limit switches were added, but it is setup to be controlled by holding the buttons.

**Comment by haywoodsloan** [comment]
Need to confirm Talon address in testing.

**Comment by alifaraji03** [comment]
Motor doesn't seem to need limit switches. So we are just going to overdrive it for now.
