### ISSUE TITLE
Flip Orientation of Drive Train with Button Press

### ISSUE THREAD

**Issue by alifaraji03** [WCR-FRC-2016/2017rep#24]
Just need to multiply joysticks values by -1 when flipping orientation. Use a toggle that multiples a global variable multiplier by -1.

**Comment by haywoodsloan** [comment]
Will now set PWM 8 to full on if the climber-side is front and PWM 9 to full on if gear-side is front.

**Comment by alifaraji03** [comment]
Fixed bug with turning being backwards. Future reference....flipping orientation keeps turning the same.
