### ISSUE TITLE
Make test cases for drive train

### ISSUE THREAD

**Issue by alifaraji03** [WCR-FRC-2016/2017rep#5]
After figuring out the drive train type and how to control it, we will need to create test cases to test the code when we are done.

**Comment by alifaraji03** [comment]
What are the requirements for this drive train? How are the controls going to be used to control the drive train?

**Comment by haywoodsloan** [comment]
Requirements:
4-6 Sim base
2 may be mini-sims
Encoders for left and right sides of drive
side motors run in unison
may get encoders on each side
Assume Arcade
Autonomous: Drive forward, turn
	-Able to be changed to add more forwards/turns
Joystick value from the controller directly proptional to the motor voltage
Make a deadband on the joystick
May need to throttle turning relative to forward speed
2-3 motors per side


Questions:
-Which way is forward?
--Make flippable
-Going backwards, which way should we turn? Like a car? Or still based on the front of the robot?
--Follow front of the robot.
-Do we need to limit the acceleration of the drive train?
 --"I hope not...." -Beau Muniz

Test Cases:
-Verify location of motors in code based on Talon LEDs WHILE THE MOTORS ARE DISCONNECTED. Make sure to not swap the motor wires afterwards.
	-Do this by using the control and seeing that the correct motor LEDs and color of LEDs match what we would expect for the controls.
	-Left joystick forward makes the robot go forward on all motors expected
	-Left joystick back makes the robot go backwards on all motors expected
	-Right joystick left makes the robot go left on all motors expected
	-Right joystick right makes the robot go right on all motors expected
	-Turning while moving forward/backward and turning while not moving forward/backward on all motors expected
	-Right joystick no movement due to y-axis
	-Left joystick no movement due to x-axis
	
-Connect the motors
	-Left joystick forward makes the robot go forward
	-Left joystick back makes the robot go backwards
	-Right joystick left makes the robot go left
	-Right joystick right makes the robot go right
	-Turning while moving forward/backward and turning while not moving forward/backward
	-Right joystick no movement due to y-axis
	-Left joystick no movement due to x-axis
	
-When joysticks are at home position, the robot will not move
-In autonomous, drive forward 5ft , turn right 90 degress, drive forward 2ft, turn left 90 degrees
-Have drive team test turning while driving forward and comment on needed changes
-Target a speed for the drive train motors, and look at feedback on RoboRio
-Verify number of encoder clicks per rotation of the wheel
